Add this feature i made
STForScratch/ScratchTools pull request #243
Opened 2022-11-11 02:13 UTC by ElPro7777

Add this feature i made Sunky scratch

2022-11-11 02:19 UTC, rgantzos requested changes
We don't need an entire extra file for the code, it won't do anything (I'm referring to Sunny-scratch.js

2022-11-11 02:21 UTC, ElPro7777 commented
its my first try to use Javascript idk what i made

2022-11-11 02:29 UTC, rgantzos commented
@ElPro7777 did you do any testing?

2022-11-21 03:08 UTC, rgantzos commented
It freezes 2.0 pages, but it won’t freeze them if you put the CSS on the main page element, not the body.

2022-12-10 04:49 UTC, veloce-vasta commented on Sunky-scratch.js
> +alert(Sunky Says: Hello)
You forgot ""

2022-12-10 04:50 UTC, veloce-vasta commented on Sunky-scratch.js
> +.rotate90 {
This is not how you insert css with js

2023-08-19 13:18 UTC, callumjt commented
loads of issues with the code and really old so it probably wont be fixed, closing

2023-08-19 13:18 UTC, closed without merging