Sidebar remade
STForScratch/ScratchTools pull request #430
Opened 2023-04-27 14:29 UTC by callumjt

completely remade sidebar
![image](https://user-images.githubusercontent.com/116295240/234893504-5ce76d47-5831-487c-b9f2-b8b907500adf.png)

changes:
- new buttons for account settings
- cleaned the code
- put the code in a folder 
- added icons

known bugs that i have no clue of fixing:
- on small screens the mail and folder buttons are off the sidebar

2023-04-27 16:39 UTC, callumjt commented on sidebar/script.js
> +                    }`;
dunno why thats bad

2023-05-06 16:23 UTC, rgantzos requested changes
The sidebar should use <a> elements for links, not JavaScript.

2023-05-06 16:26 UTC, callumjt commented
> The sidebar should use elements for links, not JavaScript.

oh ok ill work on that later

2023-08-19 13:16 UTC, callumjt commented
@Wilamaxin has made a better version cause i made this terribly lol

2023-08-19 13:16 UTC, closed without merging