Update style.css
STForScratch/ScratchTools pull request #478
Opened 2023-05-21 20:24 UTC by MaterArc

Adds a border (similar to a reported comment)

2023-05-21 23:55 UTC, rgantzos requested changes
<img width="256" alt="Screenshot 2023-05-21 at 4 54 48 PM" src="https://github.com/STForScratch/ScratchTools/assets/86856959/44d92030-b028-4c7c-93e3-c9b6a5e48f59">
This part of the bubble is missing the border.

2023-05-22 00:38 UTC, MaterArc commented
Oh, didn't notice this... Will fix it soon...

2023-05-26 14:40 UTC, MaterArc commented
@rgantzos - fixed 👍 

https://github.com/STForScratch/ScratchTools/pull/491
https://github.com/STForScratch/ScratchTools/pull/492

2023-05-28 14:42 UTC, rgantzos approved these changes

2023-05-28 14:44 UTC, merged