Fix Website Link (Aviate) To Avoid Redirect
STForScratch/ScratchTools pull request #723
Opened 2023-10-09 21:39 UTC by MaterArc

2023-10-09 21:43 UTC, rgantzos requested changes

2023-10-09 21:43 UTC, rgantzos commented on features/features.json
> +    "description": "Displays Aviate statuses on profile pages. You can set your status at https://aviate.scratchers.tech/.",
Can you please remove the https://

2023-10-09 21:47 UTC, MaterArc commented on features/features.json
> +    "description": "Displays Aviate statuses on profile pages. You can set your status at https://aviate.scratchers.tech/.",
oh forgot about that

2023-10-09 21:47 UTC, MaterArc commented on features/features.json
> +    "description": "Displays Aviate statuses on profile pages. You can set your status at https://aviate.scratchers.tech/.",
Done

2023-10-10 02:32 UTC, rgantzos approved these changes

2023-10-10 02:32 UTC, merged